#!/usr/bin/env sh

psql -c 'DROP DATABASE IF EXISTS "installation-one-test"'
psql -c 'DROP DATABASE IF EXISTS "installation-two-test"'
psql -c 'DROP DATABASE IF EXISTS "three-test"'
psql -c 'DROP DATABASE IF EXISTS "installation-unit-test"'
psql -c 'DROP DATABASE IF EXISTS "installation-inte-test"'
