#!/usr/bin/env sh

export NODE_ENV=test

npm run test:clean

# reset InstallationManager DB
knex --knexfile knexinstallationmanager.js migrate:rollback
knex --knexfile knexinstallationmanager.js migrate:latest

# run tests
#istanbul cover _mocha -- --slow 100 --timeout 10000 --reporter spec test/index.js
node test/index.js
